# Generated by Django 5.0.2 on 2024-03-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(default='admin', max_length=128, unique=True)),
                ('password', models.CharField(default='123456', max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinDiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skin_disease_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TensorflowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.CharField(max_length=4)),
                ('skin_diseases', models.CharField(blank=True, choices=[('Acne', 'Acne'), ('Eczema (Dermatitis)', 'Eczema (Dermatitis)'), ('Psoriasis', 'Psoriasis'), ('Rosacea', 'Rosacea'), ('Dermatitis Herpetiformis', 'Dermatitis Herpetiformis'), ('Skin Cancer', 'Skin Cancer'), ('Hives (Urticaria)', 'Hives (Urticaria)'), ('Vitiligo', 'Vitiligo'), ('Fungal Infections', 'Fungal Infections'), ('Scabies', 'Scabies'), ('Atopic Dermatitis', 'Atopic Dermatitis'), ('Contact Dermatitis', 'Contact Dermatitis'), ('Seborrheic Dermatitis', 'Seborrheic Dermatitis'), ('Actinic Keratosis', 'Actinic Keratosis'), ('Basal Cell Carcinoma', 'Basal Cell Carcinoma'), ('Squamous Cell Carcinoma', 'Squamous Cell Carcinoma'), ('Melanoma', 'Melanoma'), ('Keratosis Pilaris', 'Keratosis Pilaris'), ('Lichen Planus', 'Lichen Planus'), ('Pityriasis Rosea', 'Pityriasis Rosea'), ('Tinea Versicolor', 'Tinea Versicolor'), ('Impetigo', 'Impetigo'), ('Cellulitis', 'Cellulitis'), ('Molluscum Contagiosum', 'Molluscum Contagiosum'), ('Warts', 'Warts'), ('Hidradenitis Suppurativa', 'Hidradenitis Suppurativa'), ('Ichthyosis', 'Ichthyosis'), ('Folliculitis', 'Folliculitis'), ('Perioral Dermatitis', 'Perioral Dermatitis'), ('Dyshidrotic Eczema', 'Dyshidrotic Eczema'), ('Granuloma Annulare', 'Granuloma Annulare'), ('Lupus', 'Lupus'), ('Scleroderma', 'Scleroderma'), ('Epidermolysis Bullosa', 'Epidermolysis Bullosa'), ('Prurigo Nodularis', 'Prurigo Nodularis'), ('Pemphigus', 'Pemphigus'), ('Pemphigoid', 'Pemphigoid'), ('Morbilliform Drug Eruption', 'Morbilliform Drug Eruption'), ('Stevens-Johnson Syndrome', 'Stevens-Johnson Syndrome'), ('Toxic Epidermal Necrolysis', 'Toxic Epidermal Necrolysis'), ('Erythema Multiforme', 'Erythema Multiforme'), ('Cutaneous T-cell Lymphoma', 'Cutaneous T-cell Lymphoma'), ('Kaposis Sarcoma', "Kaposi's Sarcoma"), ('Pyoderma Gangrenosum', 'Pyoderma Gangrenosum'), ('Eosinophilic Pustular Folliculitis', 'Eosinophilic Pustular Folliculitis'), ('Necrobiosis Lipoidica', 'Necrobiosis Lipoidica'), ("Sweet's Syndrome", "Sweet's Syndrome"), ('Lichen Sclerosus', 'Lichen Sclerosus'), ('Pruritus', 'Pruritus'), ('Xerosis', 'Xerosis'), ('Onychomycosis', 'Onychomycosis'), ('Pilonidal Cyst', 'Pilonidal Cyst'), ('Lipoma', 'Lipoma'), ('Sebaceous Cyst', 'Sebaceous Cyst'), ('Keloids', 'Keloids'), ('Angiomas', 'Angiomas'), ('Dermatofibroma', 'Dermatofibroma')], max_length=250, null=True)),
            ],
        ),
    ]
