# Generated by Django 5.0.2 on 2024-03-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tensorflowresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
