# Generated by Django 5.0.2 on 2024-04-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospital_user_tensorflowresult_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindiseaseimage',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
    ]
